CREATE TABLE DOCUMENT
(
    DOCUMENT_ID       UUID PRIMARY KEY,
    ORGANIZATION_CODE VARCHAR(64) NOT NULL,
    CREATED_AT        TIMESTAMPTZ NOT NULL DEFAULT now(),
    RETENTION_UNTIL   TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_documents_org
    ON DOCUMENT (ORGANIZATION_CODE);

CREATE INDEX idx_documents_retention
    ON DOCUMENT (RETENTION_UNTIL);
