CREATE TABLE ATTACHMENT
(
    ATTACHMENT_ID    UUID PRIMARY KEY,
    DOCUMENT_ID      UUID         NOT NULL,

    FILE_NAME        VARCHAR(255) NOT NULL,
    LOCATION         TEXT         NOT NULL,

    FILE_IV          BYTEA        NOT NULL CHECK (octet_length(FILE_IV) = 12),
    DEK_IV           BYTEA        NOT NULL CHECK (octet_length(DEK_IV) = 12),

    ENCRYPTED_DEK    BYTEA        NOT NULL,
    KEK_VERSION      VARCHAR(64)  NOT NULL,

    ENCRYPTED_CRC32C BIGINT       NOT NULL,

    DEK_COMPROMISED  BOOLEAN      NOT NULL DEFAULT FALSE,

    CREATED_AT       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_attachment_document
        FOREIGN KEY (DOCUMENT_ID)
            REFERENCES DOCUMENT (DOCUMENT_ID)
            ON DELETE RESTRICT
);

ALTER TABLE ATTACHMENT
    ADD CONSTRAINT chk_attachment_checksum_nonzero
        CHECK (ENCRYPTED_CRC32C <> 0);

CREATE INDEX idx_attachment_document
    ON ATTACHMENT (DOCUMENT_ID);

CREATE INDEX idx_attachment_created
    ON ATTACHMENT (CREATED_AT);

CREATE INDEX idx_attachment_kek_version
    ON ATTACHMENT (KEK_VERSION);

CREATE INDEX idx_attachment_dek_compromised
    ON ATTACHMENT (DEK_COMPROMISED)
    WHERE DEK_COMPROMISED = TRUE;
