spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fenc
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
crypto:
  kek:
    keystore-type: PKCS12
    location: file:/opt/app/secrets/kek.p12
    password: ${KEK_STORE_PASSWORD}
    alias: kek-2026-04
logging:
  level:
    sun.rmi: OFF
