spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fenc
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
crypto:
  keystore:
    type: PKCS12
    location: file:/opt/app/secrets/kek.p12
    password: ${KEK_STORE_PASSWORD}
  alias:
    kek: kek-2026-04
    cek: cek202512.1
  search-key: ${SEARCH_KEY}
logging:
  level:
    sun.rmi: OFF
